# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ControledCapacityVehicleRoutingProblem',
                'doc_host': 'https://Sambosis.github.io',
                'git_url': 'https://github.com/Sambosis/ControledCapacityVehicleRoutingProblem',
                'lib_path': 'ControledCapacityVehicleRoutingProblem'},
  'syms': {}}
